{{- if .Values.gateway.hosts }}
{{- with .Values.gateway }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: main-gateway
  namespace: {{ .namespace }}
  labels:
    {{- include "miscellaneous.labels" $ | nindent 4 }}
spec:
  selector:
    istio: 
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      {{- with .hosts}}
      hosts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTP
      {{- with .hosts}}
      hosts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}