{{- if .Values.namespace }}
{{- range .Values.namespace.names }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    {{- include "miscellaneous.namespace.labels" $ | nindent 4 }}
    {{- include "miscellaneous.labels" $ | nindent 4 }}
{{- end}}
{{- end }}