{{- if .Values.namespace }}
{{- range .Values.namespace.names }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "miscellaneous.labels" $ | nindent 4 }}
{{- end}}
{{- end }}