{{- if .Values.namespace }}
{{- range .Values.namespace.names }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  {{- range $key, $value := $.Values.namespace.labels }}
  labels:
    {{- include "miscellaneous.labels" $ | nindent 4 }}
    {{- $key | nindent 4 }}: {{ $value }}
  {{- end }}
{{- end}}
{{- end }}