{{- if .Values.rbac.enabled }}
{{- range .Values.namespace.names }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "miscellaneous.fullname" $ }}-role-binding-{{ .name }}
  namespace: {{ .name }}
  labels:
    {{- include "miscellaneous.labels" $ | nindent 4}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "miscellaneous.fullname" $ }}-role-{{ .name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "miscellaneous.serviceAccountName" $ }}-{{ .name }}
    namespace: {{ .name }}
{{- end }}
{{- end }}
