{{- if .Values.rbac.enabled }}
{{- with .Values.rbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "miscellaneous.fullname" $ }}-role
  labels:
    {{- include "miscellaneous.labels" $ | nindent 4}}
  annotations:
    {{- $.Values.annotations | toYaml | nindent 4 }}
rules:
  - apiGroups: ["v1"]
    resources: ["secrets"]
    resourceNames: ["{{ include "miscellaneous.fullname" $ }}-ecr-dockercfg"]
    verbs: ["delete", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "miscellaneous.fullname" $ }}-role-binding
  labels:
    {{- include "miscellaneous.labels" $ | nindent 4}}
  annotations:
    {{- $.Values.annotations | toYaml | nindent 4 }}
roleRef:
  kind: Role
  name: {{ include "miscellaneous.fullname" $ }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "miscellaneous.serviceAccountName" $ }}
{{- end }}
{{- end }}
