{{- if .Values.rbac.enabled }}
{{- range .Values.namespace.names }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "miscellaneous.fullname" $ }}-role-{{ . }}
  namespace: {{ . }}
  labels:
    {{- include "miscellaneous.labels" $ | nindent 4}}
  annotations:
    {{- $.Values.annotations | toYaml | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["{{ include "miscellaneous.fullname" $ }}-ecr-dockercfg"]
    verbs: ["delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
{{- end }}
{{- end }}
