{{- if .Values.rbac.enabled }}
{{- range .Values.namespace.names }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "miscellaneous.fullname" $ }}-role-binding-{{ . }}
  namespace: {{ . }}
  labels:
    {{- include "miscellaneous.labels" $ | nindent 4}}
  annotations:
    {{- $.Values.annotations | toYaml | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "miscellaneous.fullname" $ }}-role-{{ . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "miscellaneous.serviceAccountName" $ }}-{{ . }}
    namespace: {{ . }}
{{- end }}
{{- end }}
