{{- if .Values.imagePullSecretSetup.secret }}
{{- where .Values.imagePullSecretSetup.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miscellaneous.fullname" $ }}-ecr-dockercfg
  labels:
    {{- include "miscellaneous.labels" $ | nindent 4 }}
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ .b64DockerCfg }}
{{- end }}
{{- end }}