{{- if .Values.imagePullSecretSetup.variables.secret }}
{{- range .Values.namespace.names }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miscellaneous.fullname" $ }}-ecr-secret
  namespace: {{ .name }}
  labels:
    {{- include "miscellaneous.labels" $ | nindent 4 }}
stringData:
  {{- toYaml $.Values.imagePullSecretSetup.variables.secret | nindent 2 }}
{{- end }}
{{- end }}
---
{{- if and .Values.imagePullSecretSetup.variables.externalSecret .Values.imagePullSecretSetup.variables.secretStoreConfiguration.enabled }}
{{- range .Values.namespace.names }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "miscellaneous.fullname" $ }}-ecr-secret
  namespace: {{ .name }}
  labels:
    {{- include "miscellaneous.labels" $ | nindent 4 }}
spec:
  secretStoreRef:
    kind: {{ $.Values.imagePullSecretSetup.variables.secretStoreConfiguration.kind }}
    name: {{ $.Values.imagePullSecretSetup.variables.secretStoreConfiguration.name }}
  target:
    name: {{ include "miscellaneous.fullname" $ }}-ecr-secret
  {{- if $.Values.imagePullSecretSetup.variables.externalSecret }}
  data:
  {{- range $key, $value := $.Values.imagePullSecretSetup.variables.externalSecret }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $value }}
  {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
