{{- if .Values.imagePullSecretSetup.enabled }}
{{- range .Values.namespace.names }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miscellaneous.fullname" $ }}-ecr-secret
  namespace: {{ . }}
  labels:
    {{- include "miscellaneous.labels" $ | nindent 4 }}
stringData:
  AWS_SECRET_ACCESS_KEY: {{ $.Values.imagePullSecretSetup.secret.secretAccessKey}}
  AWS_ACCESS_KEY_ID: {{ $.Values.imagePullSecretSetup.secret.accessKeyId}}
  AWS_ACCOUNT: {{ $.Values.imagePullSecretSetup.secret.account}}
  AWS_REGION: {{ $.Values.imagePullSecretSetup.secret.region }}
  NAMESPACE: {{ . }}
{{- end }}
{{- end }}