{{- if .Values.serviceAccount.create -}}
{{- range .Values.namespace.names }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "miscellaneous.serviceAccountName" $ }}-{{ . }}
  labels:
    {{- include "miscellaneous.labels" $ | nindent 4 }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml $ | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}