replicaCount: 1

image:
  repository: 439403303254.dkr.ecr.us-east-1.amazonaws.com/amplication-client
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: {}

environmentVariables:
  configmap: {}

healthCheck:
  enabled: false
  readinessProbe:
    enabled: false
    path: /_health/ready
  livenessProbe:
    enabled: false
    path: /_health/live

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

containerPort: 8080

service:
  type: ClusterIP
  port:
    http: 80
    https: 443

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
