{{- if .Values.environmentVariables.configMap }}
apiVersion: v1
kind: ConfigMap
  name: {{ include "generated-service.fullname" . }}
  labels:
    {{- include "generated-service.labels" . | nindent 4 }}
data: 
  {{- toYaml .Values.environmentVariables.configMap | nindent 2 }}
{{- end }}
