{{- if .Values.variables.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plugin-api.fullname" . }}-variables
  labels:
    {{- include "plugin-api.labels" . | nindent 4 }}
data: 
  {{- toYaml .Values.variables.configmap | nindent 2 }}
{{- end }}
