{{- if .Values.environmentVariables.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plugin-api.fullname" . }}
  labels:
    {{- include "plugin-api.labels" . | nindent 4 }}
data: 
  {{- toYaml .Values.environmentVariables.configmap | nindent 2 }}
{{- end }}
