apiVersion: v1
kind: Service
metadata:
  name: {{ include "plugin-api.fullname" . }}
  labels:
    {{- include "plugin-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.http }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.https }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "plugin-api.selectorLabels" . | nindent 4 }}
