environment: sandbox

istio:
  hostname: example.com
  gatewayName: main-gateway

replicaCount: 1

image:
  repository: 439403303254.dkr.ecr.us-east-1.amazonaws.com/amplication-git-pull-request-service
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

environmentVariables:
  configMap: {}
  secret: {}

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext:
securityContext:

containerPort: 3333

service:
  type: ClusterIP
  port:
    http: 80
    https: 443

volumes:
  - name: data-service-generator-main
    mountPath: /amplication-data

healthCheck:
  enabled: true
  readinessProbe:
    enabled: false
    path: /_health/ready
  livenessProbe:
    enabled: false
    path: /_health/live

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
