{{- if .Values.variables.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "git-push-webhook-service.fullname" . }}-variables
  labels:
    {{- include "git-push-webhook-service.labels" . | nindent 4 }}
data: 
  {{- toYaml .Values.variables.configmap | nindent 2 }}
{{- end }}
