{{- if .Values.variables.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "git-push-webhook-service.fullname" . }}-variables
  labels:
    {{- include "git-push-webhook-service.labels" . | nindent 4 }}
type: Opaque
data: 
  {{- toYaml .Values.variables.secret | nindent 2 }}
{{- end }}