apiVersion: v1
kind: Service
metadata:
  name: {{ include "git-push-webhook-service.fullname" . }}
  labels: {{- include "git-push-webhook-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.http }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.https }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "git-push-webhook-service.selectorLabels" . | nindent 4 }}
