apiVersion: v2
name: plugin-api
description: A Helm chart for the plugin-api component of Amplication

type: application
version: 2.0.5
appVersion: "0.0.0"

sources:
  - https://github.com/amplication/amplication

maintainers:
  - name: levi van noort
    email: levi@amplication.com
    url: https://github.com/levivannoort
