replicaCount: 1

image:
  repository: 439403303254.dkr.ecr.us-east-1.amazonaws.com/amplication-plugin-api
  pullPolicy: IfNotPresent
  tag: ""

istio:
  hostname: example.com
  gatewayName: main-gateway

environmentVariables:
  configMap: {}
  secret: {}

cronJob:
  enabled: true
  schedule: "*/10 * * * *"
  history:
    successful: 2
    failed: 2
  annotations:
    sidecar.istio.io/inject: "false"
  query: '{"query":"mutation ProcessPluginCatalog {processPluginCatalog {  name  npm  versions {    version    updatedAt    deprecated  }}}"}'

healthCheck:
  enabled: true
  readinessProbe:
    enabled: false
    path: /_health/ready
    port: 3000
  livenessProbe:
    enabled: false
    path: /_health/live
    port: 3000

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
