{{- if .Values.variables.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "build-manager.fullname" . }}-variables
  labels:
    {{- include "build-manager.labels" . | nindent 4 }}
type: Opaque
data: 
  {{- toYaml .Values.variables.secret | nindent 2 }}
{{- end }}
---
{{- if and .Values.variables.externalSecret .Values.variables.secretStoreConfiguration.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "build-manager.fullname" . }}-variables
spec:
  secretStoreRef:
    kind: {{ .Values.variables.secretStoreConfiguration.kind }}
    name: {{ .Values.variables.secretStoreConfiguration.name }}
  target:
    name: {{ include "build-manager.fullname" . }}-variables
  {{- if .Values.variables.externalSecret }}
  data:
  {{- range $key, $value := .Values.variables.externalSecret }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $value }}
  {{- end }}
  {{- end }}
{{- end }}
