apiVersion: v1
kind: Service
metadata:
  name: {{ include "client.fullname" . }}
  labels:
    {{- include "client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.targetPort}}
      protocol: TCP
      name: http
    - port: 443
      targetPort: {{ .Values.service.targetPort}}
      protocol: TCP
      name: https
  selector:
    {{- include "client.selectorLabels" . | nindent 4 }}
