nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

## @param variables.configmap A mapping of key:value to be add to the configmap object (to be used as environment variables on the deployment)
## @param variables.secret A mapping of key:value to be add to the secret object (to be used as environment variables on the deployment)
## @param variables.externalSecret A mapping of key:values to be added to the external secrets object (turned into a regular secret by the external secrets operator)
## @param variables.secretStoreConfiguration When using external secrets this part of the configuration is used to point to the secret store or cluster secret store
##
variables:
  configmap: {}
  secret: {}
  externalSecret: {}
  secretStoreConfiguration:
    kind: ClusterSecretStore
    name: ""
    enabled: false

storage:
  dataServiceGenerator:
    enabled: true
    suffix: dsg
    storageClassName: efs-dsg-sc
    persistentVolume:
      volumeHandle: <volume_handle>
  main:
    enabled: true
    suffix: main
    storageClassName: efs-main-sc
    persistentVolume:
      volumeHandle: <volume_handle>

events:
  eventSource:
    enabled: true
    name: webhook
    service:
      port: 12000
    webhook:
      endpoint: /example
      method: POST
      port: '12000'
      url: ''
  eventBus:
    enabled: true
    name: default
    native:
      replicas: 3
      auth: token
  sensor:
    image:
      repository: 439403303254.dkr.ecr.us-east-1.amazonaws.com/data-service-generator
      pullPolicy: Always
      tag: ""
    enabled: true
    name: dsg-job-webhook
    templateName: dsg-job-webhook-trigger
    generateName: dsg-job-
    ttlSecondsAfterFinished: 600
    restartPolicy: Never
    volume:
      mountPath: /efs
    variables:
      buildManagerUrl: http://build-manager
      remoteEnv: true
      buildSpecPath: /efs/input.json
      buildOutputPath: /efs/code
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 1200m
        memory: 3000Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

nodeSelector:
  role: dsg

tolerations:
  - key: dedicated
    value: dsg
