environment: sandbox

nameOverride: ""
fullnameOverride: ""

image:
  repository: 439403303254.dkr.ecr.us-east-1.amazonaws.com/data-service-generator
  pullPolicy: Always
  tag: ""

imagePullSecrets: {}

storage:
  dataServiceGenerator:
    enabled: true
    suffix: dsg
    storageClassName: efs-dsg-sc
    persistentVolume:
      volumeHandle: <path:environment-shared/data/efs/dsg/fs#volume_handle>
    persistentVolumeClaim: {}
  main:
    enabled: true
    suffix: main
    storageClassName: efs-main-sc
    persistentVolume:
      volumeHandle: <path:environment-shared/data/efs/main/fs#volume_handle>
    persistentVolumeClaim: {}

events:
  eventSource:
    enabled: true
    name: webhook
    service:
      port: 12000
    webhook:
      endpoint: /example
      method: POST
  eventBus:
    enabled: true
    name: default
    native:
      replicas: 3
      auth: token
  sensor:
    enabled: true
    name: dsg-job-webhook
    templateName: dsg-job-webhook-trigger
    generateName: dsg-job-
    ttlSecondsAfterFinished: 600
    variables:
      buildManagerUrl: http://build-manager
      remoteEnv: true
      buildSpecPath: /efs/input.json
      buildOutputPath: /efs/code

volumes:
  - name: data-service-generator-dsg-volume
    mountPath: /efs

serviceAccount:
  create: true
  annotations: {}
  name: ""

nodeSelector:
  role: dsg

tolerations:
  - key: dedicated
    value: dsg
