apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fluent-bit.fullname" . }}-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fluent-bit.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: observability
