apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.podAnnotations .Values.variables.configmap }}
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.variables.configmap }}
        checksum/config: {{ tpl ( .Files.Get "/configmap.yaml") . | sha256sum }} 
      {{- end }}
      {{- end }}
      labels:
        {{- include "server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: "{{ .Chart.Name }}-migrate"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "npx prisma migrate deploy --schema prisma/schema.prisma", ";", "exit"]
          env:
            - name: POSTGRESQL_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "server.fullname" . }}
                  key: POSTGRESQL_URL
                  optional: false
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if or .Values.variables.configmap .Values.variables.secret .Values.variables.externalSecret }}
          envFrom:
          {{- if .Values.variables.configmap }}
            - configMapRef:
                name: {{ include "server.fullname" . }}-variables
          {{- end }}
          {{- if or .Values.variables.secret .Values.variables.externalSecret }}
            - secretRef:
                name: {{ include "server.fullname" . }}-variables
          {{- end }}          
          {{- end }}
          env:
            - name: ENVIRONMENT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- if .Values.healthCheck.enabled }}
          {{- if .Values.healthCheck.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.readinessProbe.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.healthCheck.readinessProbe.initialDelaySeconds | default 5 }}
            periodSeconds: {{ .Values.healthCheck.readinessProbe.periodSeconds | default 5 }}
          {{- end }}
          {{- if .Values.healthCheck.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.livenessProbe.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.healthCheck.livenessProbe.initialDelaySeconds | default 60 }}
            periodSeconds: {{ .Values.healthCheck.livenessProbe.periodSeconds | default 60 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.volumes }}
          volumeMounts:
          {{- range .Values.volumes }}
            - name: {{ .name }}-volume
              mountPath: {{ .mountPath }}
          {{- end }}
          {{- end }}
      {{- if .Values.volumes }}
      volumes:
      {{- range .Values.volumes }}
        - name: {{ .name }}-volume
          persistentVolumeClaim:
            claimName: {{ .name }}-pvc
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
