{{- if .Values.environmentVariables.configmap }}
apiVersion: v1
kind: ConfigMap
  name: {{ include "generated-service-admin.fullname" . }}
  labels:
    {{- include "generated-service-admin.labels" . | nindent 4 }}
data: 
  {{- toYaml .Values.environmentVariables.configmap | nindent 2 }}
{{- end }}
