replicaCount: 1

image:
  repository: 439403303254.dkr.ecr.us-east-1.amazonaws.com/amplication-build-manager
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

variables:
  configmap: {}
  secret: {}

volumes:
  - name: data-service-generator-main
    mountPath: /build-artifacts
  - name: data-service-generator-dsg
    mountPath: /dsg-jobs

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

containerPort: 3333

service:
  type: ClusterIP
  port:
    http: 80
    https: 443

healthCheck:
  enabled: false
  readinessProbe:
    enabled: false
    path: /_health/ready
  livenessProbe:
    enabled: false
    path: /_health/live

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
