replicaCount: 1

image:
  repository: 439403303254.dkr.ecr.us-east-1.amazonaws.com/amplication-build-manager
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

## @param variables.configmap A mapping of key:value to be add to the configmap object (to be used as environment variables on the deployment)
## @param variables.secret A mapping of key:value to be add to the secret object (to be used as environment variables on the deployment)
## @param variables.externalSecret A mapping of key:values to be added to the external secrets object (turned into a regular secret by the external secrets operator)
## @param variables.secretStoreConfiguration When using external secrets this part of the configuration is used to point to the secret store or cluster secret store
##
variables:
  configmap: {}
  secret: {}
  externalSecret: {}
  secretStoreConfiguration:
    kind: ClusterSecretStore
    name: ""
    enabled: false

volumes:
  - name: data-service-generator-main
    mountPath: /build-artifacts
  - name: data-service-generator-dsg
    mountPath: /dsg-jobs

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

containerPort: 80

service:
  type: ClusterIP
  port:
    http: 80
    https: 443

healthCheck:
  enabled: false
  readinessProbe:
    enabled: false
    path: /_health/ready
  livenessProbe:
    enabled: false
    path: /_health/live

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
