{{- if .Values.environmentVariables.configMap }}
apiVersion: v1
kind: ConfigMap
  name: {{ include "storage-gateway.fullname" . }}
  labels:
    {{- include "storage-gateway.labels" . | nindent 4 }}
data: 
  {{- toYaml .Values.environmentVariables.configMap | nindent 2 }}
{{- end }}