{{- if .Values.variables.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "storage-gateway.fullname" . }}-variables
  labels:
    {{- include "storage-gateway.labels" . | nindent 4 }}
data: 
  {{- toYaml .Values.variables.configmap | nindent 2 }}
{{- end }}