apiVersion: v1
kind: Service
metadata:
  name: {{ include "storage-gateway.fullname" . }}
  labels:
    {{- include "storage-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.http }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.https }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "storage-gateway.selectorLabels" . | nindent 4 }}
