apiVersion: v2
name: miscellaneous
description: A Helm chart for miscellaneous resources that components of Amplication use

type: application
version: 1.1.7
appVersion: "0.0.0"

dependencies:
  - name: gateway
    alias: istio-ingress-gateway
    version: 1.15.0
    repository: https://istio-release.storage.googleapis.com/charts

sources:
  - https://github.com/amplication/amplication

maintainers:
  - name: levi van noort
    email: levi@amplication.com
    url: https://github.com/levivannoort
