namespace: 
  names:
    - sandbox
    - sandbox-dsg

imagePullSecretSetup:
  enabled: false
  cronJob:
    schedule: "*/10 * * * *"
    history:
      successful: 2
      failed: 2
    annotations:
      sidecar.istio.io/inject: "false"
  variables:
    secret: {}
    externalSecret: {}
    secretStoreConfiguration:
      kind: ClusterSecretStore
      name: ""
      enabled: false

storageClass:
  main:
    enabled: true
    name: efs-main-sc
    provisioningMode: efs-ap
    id: "<provising-id>"
    directoryPerms: '755'
    gidRangeStart: '1000'
    gidRangeEnd: '2000'
  dsg:
    enabled: true
    name: efs-dsg-sc
    provisioningMode: efs-ap
    id: '<provising-id>'
    directoryPerms: '755'
    gidRangeStart: '1000'
    gidRangeEnd: '2000'

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  enabled: true
  
annotations: {}