{{- if .Values.variables.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-service-generator.fullname" . }}-variables
  labels:
    {{- include "data-service-generator.labels" . | nindent 4 }}
data: 
  {{- toYaml .Values.variables.configmap | nindent 2 }}
{{- end }}