{{- if .Values.events.eventBus.enabled -}}
{{- with .Values.events.eventBus }}
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: {{ .name }}
  labels:
    {{- include "data-service-generator.labels" $ | nindent 4 }}
spec:
  nats:
    native:
      replicas: {{ .native.replicas }}
      auth: {{ .native.auth }}
{{- end }}
{{- end }}