{{- if .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "data-service-generator.fullname" $ }}-role-binding
  labels:
    {{- include "data-service-generator.labels" $ | nindent 4}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "data-service-generator.fullname" $ }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccountName }}
{{- end }}
