name: release helm charts
run-name: release helm charts by @${{ github.actor }}

on:
  workflow_run:
    workflows: ["lint helm charts"]
    branches: [main]
    types: 
      - completed

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: configure git (package metadata) 🔧
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: setup helm 🔧
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - name: run chart-releaser 📦
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: ./
          config: ./.github/workflows/config/helm-configuration.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"